version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sakto_backend_php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - sakto_backend_network

  db:
    image: arm64v8/mysql:8.0
    platform: linux/arm64/v8
    container_name: sakto_backend_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - backend_dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - sakto_backend_network

  nginx:
    image: nginx:alpine
    container_name: sakto_backend_nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - sakto_backend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sakto_backend_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - sakto_backend_network
    depends_on:
      - db

networks:
  sakto_backend_network:
    driver: bridge

volumes:
  backend_dbdata: 